plugins {
    id 'fabric-loom' version '1.17.17'
    id 'maven-publish'
}

version = '1.0.2'
group = 'org.adam'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://maven.lenni0451.net/releases' }
    maven { url 'https://maven.lenni0451.net/everything' }
    flatDir {
        dirs "${rootProject.projectDir}/libs"
    }
}

loom {
    splitEnvironmentSourceSets()
    mods {
        "zenithx" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

def mcVersion = property('minecraft_version') as String
def isUnobfuscated = mcVersion ==~ /^\d{2}\..*/

configurations {
    authLib
    clientImplementation.extendsFrom authLib
}

dependencies {
    minecraft "com.mojang:minecraft:${mcVersion}"

    if (!isUnobfuscated) {
        mappings loom.officialMojangMappings()
    }

    implementation "net.fabricmc:fabric-loader:${property('loader_version')}"
    implementation "net.fabricmc.fabric-api:fabric-api:${property('fabric_api_version')}"

    authLib('net.raphimc:MinecraftAuth:4.1.1') {
        exclude group: 'com.google.code.gson', module: 'gson'
        exclude group: 'org.slf4j'
    }

    implementation 'libs:discord-rpc:1.6.2'
    include 'libs:discord-rpc:1.6.2'

    include implementation('org.json:json:20231013')
    include implementation('org.java-websocket:Java-WebSocket:1.5.4')

    implementation 'com.google.code.gson:gson:2.10.1'
}

afterEvaluate {
    configurations.authLib.resolvedConfiguration.resolvedArtifacts.each { art ->
        def id = art.moduleVersion.id
        dependencies.add('include', "${id.group}:${id.name}:${id.version}")
    }
}

processResources {
    inputs.property "version", project.version
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = mcVersion.startsWith("1.20") ? 17 : (isUnobfuscated ? 25 : 21)
}

java {
    withSourcesJar()
}

jar {
    from("${rootProject.projectDir}/LICENSE") {
        rename { "${it}_${project.name}" }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
}